import { api } from "@/src/redux/base/baseApi";

export const roleSwitchSlices = api.injectEndpoints({
  endpoints: (builder) => ({
    roleSwitch: builder.mutation({
      query: () => ({
        url: "/switch-role",
        method: "POST",
      }),
      invalidatesTags: [
        "login",
        "logout",
        "register",
        "user",
        "profile",
        "promotions",
        "services",
        "provider",
        "booking",
        "delivery",
        "order",
        "dispute",
        "cart",
        "balance",
        "favorite",
        "settings",
        "message",
        "search",
        "payment",
        "notifications",
        "extend_delivery",
        "order_approve",
        "add_dispute",
        "order_reject",
        "request_delivery",
        "transactions",
        "transfer_balance",
        "withdraw",
        "services",
        "servicePost",
        "editService",
        "addServicePackageDetail",
        "deleteService",
        "addServiceAvailable",
        "updateServiceAvailable",
        "servicePackageDetails",
        "servicePackages",
        "addPortfolio",
        "updatePortfolio",
        "deletePortfolios",
        "portfolio",
        "boost",
      ],
    }),
  }),
});

export const { useRoleSwitchMutation } = roleSwitchSlices;
